var names = [];
var names2 = [];
var normalVar;
normalVar = 'sadasdf';
var newNames = ['KUMAR2', 'SURESH'];
newNames.push('ONEMORE');
names.push('kumar');
names.push('suresh');
names2.push(2134123432);
names2.push('styr');
console.log(names2);
console.log(names);
console.log(newNames);
